name: Release APK

on:
  push:
    branches:
      - production # Change to your actual production branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install dependencies
        run: npm install

      - name: Prebuild android
        run: npm run prebuild

      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease

      - name: Upload Release APK to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
